---
# Vars file for perun
# Necessary packages
prerequisites:
 Debian:
   - git
   - libswitch-perl
   - liblwp-authen-negotiate-perl
   - libjson-any-perl
   - libtext-asciitable-perl
   - libterm-readkey-perl
   - libwww-perl
   - libcrypt-ssleay-perl
   - libtext-unidecode-perl
   - libdate-calc-perl
   - libnet-ldap-perl
   - ldap-utils
   - ntp
   - rsync
   - python-passlib
   - sudo
   - whois
   - apache2
   - ntpdate
 CentOS:
   - git
   - perl-Switch
   - perl-LWP-Authen-Negotiate.noarch
   - perl-JSON-Any
   - perl-Text-ASCIITable
   - perl-TermReadKey
   - perl-libwww-perl
   - perl-Crypt-SSLeay
   - perl-Text-Unidecode
   - perl-Date-Calc
   - perl-LDAP
   - openldap-clients
   - expect
   - ntp
   - rsync
   - python-passlib
   - sudo
   - whois
   - httpd
   - ntpdate
